name: Deploy

on:
  workflow_run:
    workflows: [ "Build & test" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    strategy:
      matrix:
        project:
          - FirstWebApi
          - SecondWebApi

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install AWS Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools
      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd ./${{ matrix.project }}
          dotnet lambda deploy-function
